name: Release Theme

on:
    push:
        branches:
            - main

jobs:
    test:
        name: Build and Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn build
            - run: yarn test

    deploy:
        name: Deploy to Netlify
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn build
            - uses: netlify/actions/cli@master
              with:
                  args: deploy --dir=example-site/public --prod
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    publish:
        name: Publish to npm
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/
            - uses: actions/cache@v2
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install
            - run: yarn workspace gatsby-theme-portfolio-minimal semantic-release --branches main
              env:
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
